@extends('layouts.mobile-app')
@section('content')
<div class="p-3 pb-0">
    <a href="javascript:history.back()" class="text-decoration-none text-muted d-inline-flex align-items-center gap-2 small fw-bold">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/></svg>
        Kembali
    </a>
</div>
<style>.photo-editor{width:128px;height:128px;border-radius:28px;overflow:hidden;background:#e8efff;position:relative;margin:auto;box-shadow:0 8px 18px #14213d1a}.photo-editor img{width:100%;height:100%;object-fit:cover;display:block}.photo-placeholder{height:100%;display:grid;place-items:center;color:#246bfe;font-size:42px;font-weight:800}.range-row{display:grid;grid-template-columns:78px 1fr 38px;align-items:center;gap:10px}.range-row input{accent-color:#246bfe}</style>
<header class="mobile-hero"><div class="eyebrow">PENGATURAN AKUN</div><div class="hero-title mt-2">Edit profil</div><p class="mb-0 mt-2 opacity-75 small">Atur identitas dan tampilan foto akunmu.</p></header>
<main class="mobile-content"><div class="card mobile-card"><div class="card-body p-4"><form method="POST" action="{{ route('profile.update') }}" enctype="multipart/form-data">@csrf @method('PUT')<div class="photo-editor mb-3" id="photo-preview">@if($user->foto)<img src="{{ asset('storage/'.$user->foto) }}" alt="Preview foto profil" id="preview-image" style="object-position:{{ $user->foto_posisi_x }}% {{ $user->foto_posisi_y }}%">@else<div class="photo-placeholder" id="preview-placeholder">{{ strtoupper(substr($user->name,0,1)) }}</div><img id="preview-image" alt="Preview foto profil" style="display:none">@endif</div><label class="btn btn-outline-primary btn-sm w-100 mb-4">Pilih foto<input name="foto" id="foto-input" type="file" accept="image/jpeg,image/png,image/webp" hidden></label><div class="small text-secondary mb-3 text-center">Geser posisi foto agar bagian wajah tampil tepat.</div><div class="range-row mb-2"><label for="foto-x" class="small">Horizontal</label><input id="foto-x" name="foto_posisi_x" type="range" min="0" max="100" value="{{ old('foto_posisi_x',$user->foto_posisi_x ?? 50) }}"><output id="foto-x-value">{{ old('foto_posisi_x',$user->foto_posisi_x ?? 50) }}%</output></div><div class="range-row mb-4"><label for="foto-y" class="small">Vertikal</label><input id="foto-y" name="foto_posisi_y" type="range" min="0" max="100" value="{{ old('foto_posisi_y',$user->foto_posisi_y ?? 50) }}"><output id="foto-y-value">{{ old('foto_posisi_y',$user->foto_posisi_y ?? 50) }}%</output></div><div class="mb-3"><label class="form-label fw-semibold">Nama lengkap</label><input name="name" value="{{ old('name',$user->name) }}" class="form-control form-control-lg" required></div><div class="mb-3"><label class="form-label fw-semibold">Email</label><input name="email" type="email" value="{{ old('email',$user->email) }}" class="form-control form-control-lg" required></div><hr class="my-4"><div class="small text-secondary mb-3">Kosongkan password jika tidak ingin mengubahnya.</div><div class="mb-3"><label class="form-label fw-semibold">Password baru</label><input name="password" type="password" class="form-control form-control-lg" minlength="8"></div><div class="mb-4"><label class="form-label fw-semibold">Konfirmasi password</label><input name="password_confirmation" type="password" class="form-control form-control-lg" minlength="8"></div><button class="btn btn-primary w-100 py-3 profile-action">Simpan perubahan</button></form></div></div><a href="{{ route('profile.show') }}" class="btn btn-link w-100 mt-2 text-decoration-none">Batal</a></main>
<script>document.addEventListener('DOMContentLoaded',function(){const input=document.getElementById('foto-input');const image=document.getElementById('preview-image');const placeholder=document.getElementById('preview-placeholder');const x=document.getElementById('foto-x');const y=document.getElementById('foto-y');const xv=document.getElementById('foto-x-value');const yv=document.getElementById('foto-y-value');function position(){image.style.objectPosition=x.value+'% '+y.value+'%';xv.value=x.value+'%';yv.value=y.value+'%'}x.addEventListener('input',position);y.addEventListener('input',position);input.addEventListener('change',function(){if(!input.files[0])return;image.src=URL.createObjectURL(input.files[0]);image.style.display='block';if(placeholder)placeholder.style.display='none';position()});position()});</script>
@endsection
