@extends('layouts.mobile-app')
@section('content')
<div class="p-3 pb-0">
    <a href="javascript:history.back()" class="text-decoration-none text-muted d-inline-flex align-items-center gap-2 small fw-bold">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/></svg>
        Kembali
    </a>
</div>
<header class="mobile-hero"><div class="eyebrow mt-4">DATA PEMBAYARAN</div><div class="hero-title mt-2">Catat SPP siswa</div></header><main class="mobile-content"><div class="card mobile-card"><div class="card-body p-4"><form method="POST" action="{{ route('spp.store') }}">@csrf<div class="mb-3"><label class="form-label fw-semibold">Siswa</label><select name="siswa_id" class="form-select" required><option value="">Pilih siswa</option>@foreach($siswas as $siswa)<option value="{{ $siswa->id }}">{{ $siswa->name }}</option>@endforeach</select></div><div class="row g-3"><div class="col-6"><label class="form-label fw-semibold">Bulan</label><input name="bulan" type="number" min="1" max="12" class="form-control" required></div><div class="col-6"><label class="form-label fw-semibold">Tahun</label><input name="tahun" type="number" min="2020" value="{{ date('Y') }}" class="form-control" required></div><div class="col-6"><label class="form-label fw-semibold">Nominal</label><input name="nominal" type="number" min="0" class="form-control" required></div><div class="col-6"><label class="form-label fw-semibold">Sudah dibayar</label><input name="dibayar" type="number" min="0" value="0" class="form-control"></div></div><div class="mt-3"><label class="form-label fw-semibold">Jatuh tempo</label><input name="jatuh_tempo" type="date" class="form-control"></div><button class="btn btn-primary w-100 py-3 mt-4 profile-action">Simpan data SPP</button></form></div></div></main>@endsection
