<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <title>{{ $title ?? 'Portal Sekolah' }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        :root{--ink:#14213d;--muted:#738097;--blue:#246bfe;--surface:#f5f7fb;--danger:#d63f55;--top-height:70px;--bottom-height:0px}
        *{box-sizing:border-box}html,body{height:100%;margin:0}body{background:var(--surface);color:var(--ink);font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overflow:hidden}
        .mobile-shell{width:100%;max-width:680px;height:100vh;margin:auto;overflow-y:auto;padding:calc(var(--top-height) + 12px) 0 calc(var(--bottom-height) + 16px);scroll-behavior:smooth}
        .page-header{position:fixed;z-index:30;top:0;left:0;right:0;height:var(--top-height);background:#fffffff5;border-bottom:1px solid #e8ecf3;backdrop-filter:blur(14px);display:flex;align-items:center;justify-content:center}
        .page-header-inner{width:min(680px,100%);padding:0 20px;display:flex;align-items:center;justify-content:space-between}.page-title{font-size:13px;font-weight:800;color:var(--ink);letter-spacing:.02em}.page-back{display:inline-flex;align-items:center;justify-content:center;gap:7px;padding:10px 17px;background:var(--danger);color:#fff;text-decoration:none;font-size:12px;font-weight:800;border-radius:999px;box-shadow:0 7px 17px #d63f5538;transition:transform .2s,box-shadow .2s}.page-back:hover,.page-back:active{color:#fff;transform:translateY(-2px);box-shadow:0 11px 22px #d63f5555}
        .mobile-hero{background:linear-gradient(140deg,#14213d,#246bfe);color:#fff;border-radius:0 0 30px 30px;padding:24px 20px 30px}.eyebrow{font-size:11px;letter-spacing:.13em;opacity:.75;font-weight:800}.hero-title{font-size:26px;font-weight:800;letter-spacing:-.02em}.avatar{width:48px!important;min-width:48px;max-width:48px;height:48px!important;min-height:48px;max-height:48px;flex:0 0 48px;aspect-ratio:1/1;overflow:hidden;display:grid;place-items:center;flex-shrink:0;border-radius:17px;background:#ffffff2b;font-weight:800;font-size:18px}.avatar img{display:block;width:100%!important;height:100%!important;max-width:none;max-height:none;object-fit:cover}.class-pill{display:inline-block;background:#ffffff20;border:1px solid #ffffff42;border-radius:99px;padding:6px 12px;font-size:12px}.mobile-content{padding:20px}.section-title{font-size:17px;font-weight:800}.mobile-card{border:0;border-radius:20px;box-shadow:0 8px 24px #14213d12;animation:rise .45s both}.tap-card{transition:transform .2s,box-shadow .2s}.tap-card:hover,.tap-card:active{transform:translateY(-3px);box-shadow:0 13px 28px #14213d1c}.icon-box{width:43px;height:43px;border-radius:14px;display:grid;place-items:center;font-size:20px;background:#e8efff;color:var(--blue)}.profile-action{border-radius:14px}.submission-progress{border-radius:12px}.chat-bubble{max-width:86%;padding:10px 13px;border-radius:16px 16px 16px 5px;background:#fff;box-shadow:0 5px 16px #14213d0d;font-size:13px}.chat-bubble.mine{background:#246bfe;color:#fff;border-radius:16px 16px 5px}.chat-composer{position:fixed;z-index:40;left:50%;bottom:var(--bottom-height);transform:translateX(-50%);width:min(680px,100%);background:#f5f7fb;padding:8px 20px;border-top:1px solid #e8ecf3}.chat-composer .form-control{border:0;box-shadow:0 5px 16px #14213d12}.chat-composer .btn{border-radius:12px}.emoji-button{border:0}.emoji-pick{font-size:16px;padding:0 4px}.logout-panel{display:flex;align-items:center;justify-content:space-between;gap:14px;border:1px solid #f1d8dd;background:#fff5f6;border-radius:20px;padding:16px}.logout-panel .btn{border-radius:12px;white-space:nowrap}.stagger>*{animation:rise .45s both}.stagger>*:nth-child(2){animation-delay:.08s}.stagger>*:nth-child(3){animation-delay:.16s}@keyframes rise{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;transition-duration:.01ms!important}}@media(min-width:681px){.mobile-shell{height:calc(100vh - 40px);margin-top:20px}.page-header{top:20px}.page-footer{bottom:20px}}
    </style>
</head>
<body>
    <header class="page-header"><div class="page-header-inner"><a href="{{ route('dashboard') }}" class="page-back">&larr; Beranda</a><span class="page-title">APP MAHASISWA</span></div></header>
    <main class="mobile-shell">@yield('content')</main>
</body>
</html>
